import { ctx } from '@/server/bootstrap';
import { msg, type SearchParams } from '@/lib/range';
import { getConnection } from '@/server/crm/connection';
import { mirrorCounts } from '@/server/crm/mirror';
import { CRM_BACKEND_URL, CRM_CONFIGURED } from '@/server/crm/client';
import { scalar, isDemoMode } from '@/server/db';
import { crmConnectAction, crmSyncAction, crmDisconnectAction, crmForgetLinksAction } from '@/app/actions';
import {
  PageHeader, Card, Banner, Field, inputClass, btn, StatTile, DefList, LinkButton,
} from '@/components/ui';

export const dynamic = 'force-dynamic';

/**
 * A sync is several round trips to the CRM and a few hundred draft documents,
 * which is well past the ten seconds a serverless function gets by default.
 * The ceiling applies to the server actions invoked from this page too, which
 * is the one that actually matters — `crmSyncAction` is the long call, not the
 * render.
 */
export const maxDuration = 60;

/**
 * Settings → CRM Sync. The UNATTENDED half of the connection.
 *
 * -------------------------------------------------------------------------
 * WHAT THIS SCREEN IS FOR, NOW THAT FETCHING DOES NOT NEED IT
 * -------------------------------------------------------------------------
 * An accountant who is signed in can already fetch from TripzoCRM → Invoices
 * on their own token — they are authenticated as the same person, and asking
 * them to configure a second credential for the same account would be a setup
 * step with no purpose behind it.
 *
 * What a stored connection buys is the case where nobody is watching: a
 * SERVICE identity, one per set of books, that still works at 3am and survives
 * the person who configured it logging out. Where both exist the stored one is
 * preferred, so a scheduled run and a manual one behave identically rather
 * than differing by who happened to press the button.
 *
 * WHY THERE IS A PASSWORD BOX HERE AT ALL. The CRM backend authenticates a
 * PERSON, not an application: it resolves the caller's organisation from their
 * Supabase token and there is no service account to issue instead. So the
 * accountant signs in as themselves. The password is posted once, exchanged
 * for a token, and never stored — see src/server/crm/client.ts. What is kept
 * is the token and its refresh token, both revocable from the CRM.
 *
 * -------------------------------------------------------------------------
 * AND THE DIRECTION IS ONE-WAY
 * -------------------------------------------------------------------------
 * Connecting grants this app READ access to the agency's CRM and nothing else.
 * `crmFetch` has no method and no body parameter, so no screen, action or job
 * in this product can alter a TripzoCRM record — the guarantee is structural
 * rather than a promise on a settings page.
 */
export default async function CrmSyncPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const s = await ctx();
  const m = await msg(await searchParams);
  const conn = await getConnection(s.orgId);
  const demo = isDemoMode();

  const imported = {
    partners: await scalar("SELECT COUNT(*) FROM crm_links WHERE org_id=? AND kind='partner'", s.orgId),
    bookings: await scalar("SELECT COUNT(*) FROM crm_links WHERE org_id=? AND kind='booking'", s.orgId),
  };
  /*
   * FETCHED AND DRAFTED ARE TWO DIFFERENT NUMBERS, and showing only one of them
   * is how an invoice goes missing quietly. "Fetched" counts what this database
   * holds a copy of; "in the books" counts what became a document. The gap
   * between them is sales that are in no balance, no report and no return — so
   * it is the figure this card leads with rather than one somebody has to
   * subtract.
   */
  const crm = await mirrorCounts(s.orgId);
  const waiting = crm.invoices - crm.imported;

  return (
    <>
      <PageHeader
        title="CRM Sync"
        subtitle="A stored, unattended connection to TripzoCRM. Read-only over there; drafts over here. A fetch types, an accountant posts."
        accent="var(--color-sec-settings)"
        actions={<LinkButton href="/settings">Back to settings</LinkButton>}
      />
      {m.error && <Banner tone="error">{m.error}</Banner>}
      {m.ok && <Banner tone="ok">{m.ok}</Banner>}

      {/*
        * Two different reasons the button can be dead, and they deserve
        * different sentences. In a demo nothing is wrong and the screen is
        * being shown deliberately; missing a key on a real deployment is a
        * setup step somebody still has to do.
        */}
      {demo ? (
        <Banner tone="info">
          <b>Demo mode.</b> The books on screen are sample data generated by this app, and there is no
          connection to TripzoCRM. Syncing is switched off so a demonstration cannot reach a live agency.
          Set <code>TRIPZO_DATABASE_URL</code> and the <code>TRIPZO_SUPABASE_*</code> values to connect
          for real.
        </Banner>
      ) : !CRM_CONFIGURED && (
        <Banner tone="warn">
          <code>TRIPZO_SUPABASE_ANON_KEY</code> is not set. Copy it from{' '}
          <code>tripzo-crm-mobile/.env</code> into this app&apos;s <code>.env.local</code>, then restart the
          dev server. The key is public by design — it is inlined into the mobile bundle — but it is not
          committed here.
        </Banner>
      )}

      <div className="grid gap-5 lg:grid-cols-[1.3fr_1fr]">
        <div className="space-y-5">
          {conn ? (
            <Card title="Connected" subtitle={`Signed in to ${CRM_BACKEND_URL}`}>
              <DefList rows={[
                ['Signed in as', conn.email],
                ['Agency', conn.crm_org_name ?? s.orgName],
                ['Last sync', conn.last_sync_at
                  ? new Date(conn.last_sync_at).toLocaleString('en-IN')
                  : 'Never'],
                ['Last result', conn.last_result ?? '—'],
              ]} />

              <div className="mt-5 flex flex-wrap items-center gap-2">
                <form action={crmSyncAction}>
                  <button className={btn.primary}>Fetch &amp; import now</button>
                </form>
                <form action={crmDisconnectAction}>
                  <button className={btn.ghost}>Disconnect</button>
                </form>
              </div>

              <p className="mt-3 text-[12px] text-ink-faint">
                A fetch copies every CRM invoice, line and receipt into this database and drafts a
                document for whatever is not in the books yet. Re-running it is safe: a record
                already imported is matched to what it became and skipped, so nothing arrives twice
                — and a doubled posting is the one mistake that leaves a ledger balanced and wrong.
              </p>
              <div className="mt-4 space-y-3">
                <Banner tone="info">
                  <strong>A fetch posts nothing.</strong> Invoices and receipts land as drafts in{' '}
                  <a href="/accounting/review" className="font-bold text-brand hover:underline">
                    Accounting → Review &amp; Post
                  </a>
                  , where you check the accounts, the tax and the trip each one is tagged to, and
                  post it yourself. Until you do, none of it is in a balance, a report or a return.
                </Banner>
                <Banner tone="ok">
                  <strong>Nothing is ever written to TripzoCRM.</strong> This connection is
                  read-only by construction — the CRM client has no method or body parameter, so no
                  screen, action or scheduled job in this product can change an invoice, a receipt or
                  a status over there. Every edit happens on the ledger document in this app&rsquo;s own
                  database.
                </Banner>
              </div>
            </Card>
          ) : (
            <Card title="Connect to TripzoCRM"
              subtitle="Your own CRM sign-in. The password is exchanged for a token and never stored.">
              <form action={crmConnectAction} className="space-y-4">
                <Field label="CRM email">
                  <input name="email" type="email" required autoComplete="username"
                    className={inputClass} placeholder="you@wandertravels.in" />
                </Field>
                <Field label="Password" hint="Used for this one sign-in call. Not written to the database or the audit log.">
                  <input name="password" type="password" required autoComplete="current-password"
                    className={inputClass} />
                </Field>
                <button className={btn.primary} disabled={demo || !CRM_CONFIGURED}>Connect</button>
              </form>
            </Card>
          )}

          <Card title="What a fetch brings across">
            <ol className="space-y-3 text-[13.5px]">
              <Step n={1} title="The agency">
                Its name replaces whatever this app was seeded with — that is the string on the
                masthead and every report header. Checked first against the agency these books
                belong to: a token resolving to a different agency aborts the run before a single
                record is read.
              </Step>
              <Step n={2} title="Suppliers and leads">
                Suppliers become payable partners; leads become customers. A lead that has reached a
                trip also becomes a booking, with the analytic account that lets costs be tagged to
                it.
              </Step>
              <Step n={3} title="Every invoice, copied into this database">
                Header, lines, receipts and the whole raw payload, in paise, with the moment it was
                read. This is the copy the books are drafted from and the copy they keep answering
                for — a figure already in a filed return must not move because somebody edited a row
                in the CRM afterwards.
              </Step>
              <Step n={4} title="Documents, as drafts">
                Everything except a cancelled invoice. A CRM draft is imported too, flagged as one:
                an agent raises the invoice over there with no books fields on it at all, and
                completing it here is the work. Each one arrives with the customer, the trip, the
                dates, the lines, the amounts, the place of supply and the GSTIN already filled in,
                and the revenue account and GST rate inferred per line where they could be.
              </Step>
              <Step n={5} title="Receipts and advances, as drafts">
                A payment dated before its invoice is an <strong>advance</strong>: section 13(2)
                makes the GST on it due in the month the money arrived, so it is drafted on Customer
                Advances with the tax backed out of it. One dated on or after the invoice is an
                ordinary receipt. The CRM draws no distinction, so this does — once, at fetch time,
                written down rather than re-derived later.
              </Step>
              <Step n={6} title="Nothing else, ever">
                No journal entry, no tax posting and no balance moves because of a fetch. The only
                thing that writes to these books is somebody pressing Post. And nothing at all is
                written to TripzoCRM.
              </Step>
            </ol>
          </Card>
        </div>

        <div className="space-y-5">
          <Card title="Fetched and drafted" subtitle="What this database holds, and how much of it has reached the books.">
            <div className="grid grid-cols-2 gap-3">
              <StatTile label="Invoices fetched" value={String(crm.invoices)} />
              <StatTile label="In the books" value={String(crm.imported)}
                tone={waiting > 0 ? 'warn' : 'positive'}
                hint={waiting > 0 ? `${waiting} still waiting` : undefined} />
              <StatTile label="Receipts fetched" value={String(crm.payments)} />
              <StatTile label="Receipts drafted" value={String(crm.paid_imported)} />
              <StatTile label="Partners" value={String(imported.partners)} />
              <StatTile label="Bookings" value={String(imported.bookings)} />
            </div>
            {waiting > 0 && (
              <p className="mt-3 text-[12px] text-ink-faint">
                {waiting} fetched invoice(s) have no document behind them, so those sales are in no
                balance and no return.{' '}
                <a href="/crm/invoices" className="font-bold text-brand hover:underline">
                  See which, and why
                </a>
                .
              </p>
            )}
          </Card>

          <Card title="Clear import history">
            <p className="mb-3 text-[13px] text-ink-muted">
              Forgets which CRM record became which local record, so the next fetch imports
              everything again. The copies of the CRM&rsquo;s own invoices are kept — what the CRM said
              is a reading of history and is worth having whatever happens to the books drafted from
              it.
            </p>
            {/*
              Said plainly, because the obvious assumption about a button like
              this is the dangerous one. It is not an undo: the postings the
              earlier import made are still in the ledger and will still be,
              afterwards, alongside the new ones.
            */}
            <Banner tone="warn">
              This does not delete anything already posted. A posted entry is never deleted in this
              system — so re-importing creates a <strong>second</strong> copy of every invoice, not a
              replacement. Use it only on books you intend to reset.
            </Banner>
            <form action={crmForgetLinksAction} className="space-y-3">
              <Field label="Type FORGET to confirm">
                <input name="confirm" className={inputClass} placeholder="FORGET" />
              </Field>
              <button className={btn.danger}>Clear import history</button>
            </form>
          </Card>
        </div>
      </div>
    </>
  );
}

function Step({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  return (
    <li className="flex gap-3">
      <span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-canvas text-[12px] font-bold text-ink-muted">
        {n}
      </span>
      <span>
        <span className="font-bold">{title}. </span>
        <span className="text-ink-muted">{children}</span>
      </span>
    </li>
  );
}
